### ISSUE TITLE
Proposal : giving an option to install grub2 instead of refind for bios installation.

### ISSUE THREAD

**Issue by FredBezies** [VeltTechnologies/vos-installer#3]
A follow up bug #2 : wouldn't it a great idea to install grub2 for bios installation?

**Comment by azsn** [comment]
No. UEFI has been around for over a decade, practically every computer since around 2012 comes with UEFI-compatible hardware, and virtual machine software including VirtualBox and QEMU support UEFI emulation as well. If someone wants to add BIOS bootloader support to the installer and make a pull request, sure, but I don't want to waste time supporting legacy hardware.

**Comment by coderobe** [comment]
Note: This wont stop you from installing grub manually if you feel like it. You can follow the instructions on the arch wiki for that.
